-- INSERT INTO CUSTOMER_CATALOGUE.USER_CREDENTIALS (USERNAME, PASSWORD) VALUES ('rahul', 'dravid');
-- INSERT INTO CUSTOMER_CATALOGUE.USER_CREDENTIALS (USERNAME, PASSWORD) VALUES ('virat', 'kohli');

INSERT INTO `customer_catalogue`.`USER_CREDENTIALS` (`USERNAME`, `PASSWORD`) VALUES ('rahul', 'dravid');
INSERT INTO `customer_catalogue`.`USER_CREDENTIALS` (`USERNAME`, `PASSWORD`) VALUES ('virat', 'kohli');